// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qnhtthhccyhxuqmvosms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuaHR0aGhjY3loeHVxbXZvc21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODQ2NjgsImV4cCI6MjA3MDA2MDY2OH0.cstAS5I6aUNt6_8Sipj1DPzowdSLSpmviQW435fzozU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);